# Generated by Django 2.0 on 2018-02-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180217_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='total',
            field=models.TextField(default='0000000', editable=False, max_length=30),
        ),
    ]
