# Generated by Django 2.0 on 2018-02-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180217_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='total',
            new_name='data',
        ),
    ]
